apiVersion: deploy.cloud.google.com/v1
kind: Target

metadata:
  name: dev
  annotations: {}
  labels: {}

description: dev

gke:
  cluster: projects/project-62ad09b9-d8ae-4ae2-8db/locations/us-central1-a/clusters/cluster-1