apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 3

  selector:
    matchLabels:
      app: app1

  template:
    metadata:
      labels:
        app: app1

    spec:
      containers:
        - name: app1-container
          image: us-central1-docker.pkg.dev/project-62ad09b9-d8ae-4ae2-8db/gke-repo/quickstart-image
          ports:
            - containerPort: 8080