apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container-1
        image: us-central1-docker.pkg.dev/project-62ad09b9-d8ae-4ae2-8db/gke-repo/quickstart-image
        ports:
        - containerPort: 8080